export const CONSENT_PURPOSES = [
  'TELECONSULTATION', 'PRESCRIPTION_PHARMACY', 'LAB_PROCESSING',
  'HEALTH_DATA_ANALYTICS', 'MARKETING_COMMUNICATIONS', 'PHOTO_AI_PROCESSING',
] as const
export type ConsentPurpose = (typeof CONSENT_PURPOSES)[number]
