export const CONSULTATION_STATUSES = [
  'SUBMITTED', 'AI_PROCESSING', 'AI_FAILED', 'AI_COMPLETE', 'ASSIGNED', 'REVIEWING',
  'MORE_INFO_REQUESTED', 'LAB_ORDERED', 'PRESCRIBED', 'AWAITING_PAYMENT', 'EXPIRED_UNPAID',
  'REFERRED', 'DECLINED', 'PAYMENT_COMPLETE', 'PHARMACY_PROCESSING', 'DISPATCHED',
  'DELIVERED', 'TREATMENT_ACTIVE', 'FOLLOW_UP_DUE', 'COMPLETED', 'CANCELLED', 'ABANDONED',
] as const
export type ConsultationStatus = (typeof CONSULTATION_STATUSES)[number]
