export const LAB_ORDER_STATUSES = [
  'ORDERED', 'SLOT_BOOKED', 'NURSE_ASSIGNED', 'NURSE_EN_ROUTE', 'NURSE_ARRIVED',
  'SAMPLE_COLLECTED', 'AT_LAB', 'SAMPLE_RECEIVED', 'PROCESSING', 'RESULTS_UPLOADED',
  'RESULTS_READY', 'DOCTOR_REVIEWED', 'CLOSED', 'COLLECTION_FAILED', 'SAMPLE_ISSUE',
  'RECOLLECTION_NEEDED', 'CANCELLED',
] as const
export type LabOrderStatus = (typeof LAB_ORDER_STATUSES)[number]
export const LAB_PAYMENT_STATUSES = ['PENDING', 'WAIVED_INITIAL', 'INCLUDED', 'PAID'] as const
export type LabPaymentStatus = (typeof LAB_PAYMENT_STATUSES)[number]
