// convex/biomarker/lib/autoDraftRange.ts
//
// Layer C of the auto-classification pipeline: generate a DRAFT reference
// range for a marker that never classified against the reference DB AND
// didn't match any alias fuzzily. Gated by:
//   1. Cooling-off — queue occurrenceCount must be >= COOLING_OFF_THRESHOLD
//      so we don't waste a second Claude call on one-off typos.
//   2. Claude's canonical_id_guess must be non-null — if the primary extractor
//      had no opinion, neither will the secondary generator.
//   3-8. Output-shape gates (see handler).
//
// DRAFT rows land with clinicalReviewer = "DRAFT — auto-generated YYYY-MM-DD"
// and autoGenerated: true. A clinician reviews and stamps before the range
// is considered trusted. Until then the range IS active — reclassify will
// pick it up on the next sighting.

import { internal } from "../../_generated/api";
import type { Id } from "../../_generated/dataModel";
import type { ActionCtx } from "../../_generated/server";
import {
  callAutoDraftRange,
  ALLOWED_CATEGORIES,
  type AutoDraftRangeOutput,
} from "../../lib/claude";

export const MIN_CONFIDENCE = 0.75;
export const COOLING_OFF_THRESHOLD = 3;

interface Args {
  nameOnReport: string;
  rawUnit: string | null;
  labPrintedRange: string | null;
  canonicalIdGuess: string | null;
  queueOccurrenceCount: number;
}

export interface AutoDraftResult {
  outcome:
    | "wrote_range"
    | "rejected_not_biomarker"
    | "rejected_low_confidence"
    | "rejected_bad_category"
    | "rejected_bad_thresholds"
    | "rejected_missing_citation"
    | "rejected_cooling_off";
  canonicalId?: string;
  rangeId?: Id<"biomarker_reference_ranges">;
}

function thresholdsValid(o: AutoDraftRangeOutput): boolean {
  const below = [o.action_below, o.sub_optimal_below_min, o.optimal_min];
  const above = [o.optimal_max, o.sub_optimal_above_max, o.action_above];
  const present = [...below, ...above].filter((x) => x !== null) as number[];
  if (present.length < 2) return false;
  for (let i = 0; i < below.length - 1; i++) {
    const a = below[i];
    const b = below[i + 1];
    if (a !== null && b !== null && !(a < b)) return false;
  }
  if (
    o.optimal_min !== null &&
    o.optimal_max !== null &&
    !(o.optimal_min <= o.optimal_max)
  ) {
    return false;
  }
  for (let i = 0; i < above.length - 1; i++) {
    const a = above[i];
    const b = above[i + 1];
    if (a !== null && b !== null && !(a < b)) return false;
  }
  return true;
}

export async function autoGenerateDraftRange(
  ctx: ActionCtx,
  args: Args,
): Promise<AutoDraftResult> {
  // GATE 1: cooling-off threshold
  if (args.queueOccurrenceCount < COOLING_OFF_THRESHOLD) {
    return { outcome: "rejected_cooling_off" };
  }
  // GATE 2: Claude's guess must be non-null
  if (args.canonicalIdGuess === null) {
    return { outcome: "rejected_not_biomarker" };
  }

  const output = await callAutoDraftRange({
    nameOnReport: args.nameOnReport,
    rawUnit: args.rawUnit,
    labPrintedRange: args.labPrintedRange,
    canonicalIdGuess: args.canonicalIdGuess,
  });

  // GATE 3: is_real_biomarker
  if (!output.is_real_biomarker) {
    return { outcome: "rejected_not_biomarker" };
  }
  // GATE 4: confidence
  if (output.confidence < MIN_CONFIDENCE) {
    return { outcome: "rejected_low_confidence" };
  }
  // GATE 5: category whitelist
  if (
    !output.category ||
    !(ALLOWED_CATEGORIES as readonly string[]).includes(output.category)
  ) {
    return { outcome: "rejected_bad_category" };
  }
  // GATE 6: source citation present
  if (!output.source_citation || output.source_citation.trim().length === 0) {
    return { outcome: "rejected_missing_citation" };
  }
  // GATE 7: threshold ordering
  if (!thresholdsValid(output)) {
    return { outcome: "rejected_bad_thresholds" };
  }
  // GATE 8: all schema-required fields present (the shape insertReferenceRange
  // enforces but gate early to keep the outcome enum meaningful).
  if (
    !output.canonical_id ||
    !output.display_name ||
    !output.canonical_unit ||
    output.age_min === null ||
    output.age_max === null ||
    output.sex === null ||
    output.pregnancy_sensitive === null ||
    output.optimal_min === null ||
    output.optimal_max === null
  ) {
    return { outcome: "rejected_bad_thresholds" };
  }

  const todayIso = new Date().toISOString().slice(0, 10);
  const rangeId = await ctx.runMutation(
    internal.biomarker.internalMutations.insertReferenceRange,
    {
      canonicalId: output.canonical_id,
      displayName: output.display_name,
      aliases: output.aliases,
      category: output.category,
      canonicalUnit: output.canonical_unit,
      ageMin: output.age_min,
      ageMax: output.age_max,
      sex: output.sex,
      pregnancySensitive: output.pregnancy_sensitive,
      optimalMin: output.optimal_min,
      optimalMax: output.optimal_max,
      subOptimalBelowMin: output.sub_optimal_below_min ?? undefined,
      subOptimalAboveMax: output.sub_optimal_above_max ?? undefined,
      actionBelow: output.action_below ?? undefined,
      actionAbove: output.action_above ?? undefined,
      explainer: output.explainer ?? "",
      source: output.source_citation,
      clinicalReviewer: `DRAFT — auto-generated ${todayIso}`,
      isActive: true,
      autoGenerated: true,
      now: Date.now(),
    },
  );

  return { outcome: "wrote_range", canonicalId: output.canonical_id, rangeId };
}
