import { describe, it, expect, vi, beforeEach } from "vitest";

// Mock the Claude helper to avoid live API calls. autoGenerateDraftRange
// exercises the gate ladder; only the happy path needs the mutation call.
vi.mock("../../lib/claude", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../../lib/claude")>();
  return {
    ...actual,
    callAutoDraftRange: vi.fn(),
  };
});

import { autoGenerateDraftRange } from "../../biomarker/lib/autoDraftRange";
import { callAutoDraftRange } from "../../lib/claude";

const mockCtx = (mutationReturn = "range-id") =>
  ({
    runMutation: vi.fn(async () => mutationReturn),
  }) as unknown as Parameters<typeof autoGenerateDraftRange>[0];

describe("autoGenerateDraftRange gates", () => {
  beforeEach(() => vi.clearAllMocks());

  it("rejects when occurrenceCount < cooling-off threshold", async () => {
    const result = await autoGenerateDraftRange(mockCtx(), {
      nameOnReport: "x",
      rawUnit: null,
      labPrintedRange: null,
      canonicalIdGuess: "x",
      queueOccurrenceCount: 2,
    });
    expect(result.outcome).toBe("rejected_cooling_off");
  });

  it("rejects when canonicalIdGuess is null", async () => {
    const result = await autoGenerateDraftRange(mockCtx(), {
      nameOnReport: "x",
      rawUnit: null,
      labPrintedRange: null,
      canonicalIdGuess: null,
      queueOccurrenceCount: 3,
    });
    expect(result.outcome).toBe("rejected_not_biomarker");
  });

  it("rejects when Claude says is_real_biomarker=false", async () => {
    vi.mocked(callAutoDraftRange).mockResolvedValue({
      is_real_biomarker: false,
      canonical_id: null,
      display_name: null,
      aliases: [],
      category: null,
      canonical_unit: null,
      sex: null,
      age_min: null,
      age_max: null,
      pregnancy_sensitive: null,
      optimal_min: null,
      optimal_max: null,
      sub_optimal_below_min: null,
      sub_optimal_above_max: null,
      action_below: null,
      action_above: null,
      explainer: null,
      source_citation: null,
      confidence: 0.9,
    });
    const result = await autoGenerateDraftRange(mockCtx(), {
      nameOnReport: "HEM-401",
      rawUnit: null,
      labPrintedRange: null,
      canonicalIdGuess: "hem",
      queueOccurrenceCount: 5,
    });
    expect(result.outcome).toBe("rejected_not_biomarker");
  });

  it("rejects when confidence below threshold", async () => {
    vi.mocked(callAutoDraftRange).mockResolvedValue({
      is_real_biomarker: true,
      canonical_id: "ast",
      display_name: "AST",
      aliases: [],
      category: "Liver",
      canonical_unit: "U/L",
      sex: "any",
      age_min: 18,
      age_max: 120,
      pregnancy_sensitive: false,
      optimal_min: 10,
      optimal_max: 40,
      sub_optimal_below_min: 5,
      sub_optimal_above_max: 60,
      action_below: 3,
      action_above: 100,
      explainer: "liver enzyme",
      source_citation: "NIH",
      confidence: 0.5,
    });
    const result = await autoGenerateDraftRange(mockCtx(), {
      nameOnReport: "Aspartate Aminotransferase",
      rawUnit: "U/L",
      labPrintedRange: "5-40",
      canonicalIdGuess: "ast_sgot",
      queueOccurrenceCount: 5,
    });
    expect(result.outcome).toBe("rejected_low_confidence");
  });

  it("rejects when category not in whitelist", async () => {
    vi.mocked(callAutoDraftRange).mockResolvedValue({
      is_real_biomarker: true,
      canonical_id: "foo",
      display_name: "Foo",
      aliases: [],
      category: "Cardiac Biomarkers",
      canonical_unit: "ng/L",
      sex: "any",
      age_min: 18,
      age_max: 120,
      pregnancy_sensitive: false,
      optimal_min: 0,
      optimal_max: 14,
      sub_optimal_below_min: null,
      sub_optimal_above_max: 50,
      action_below: null,
      action_above: 100,
      explainer: "x",
      source_citation: "ref",
      confidence: 0.95,
    });
    const result = await autoGenerateDraftRange(mockCtx(), {
      nameOnReport: "Troponin I",
      rawUnit: "ng/L",
      labPrintedRange: null,
      canonicalIdGuess: "troponin",
      queueOccurrenceCount: 5,
    });
    expect(result.outcome).toBe("rejected_bad_category");
  });

  it("rejects on bad threshold ordering", async () => {
    vi.mocked(callAutoDraftRange).mockResolvedValue({
      is_real_biomarker: true,
      canonical_id: "x",
      display_name: "X",
      aliases: [],
      category: "Liver",
      canonical_unit: "U/L",
      sex: "any",
      age_min: 18,
      age_max: 120,
      pregnancy_sensitive: false,
      optimal_min: 50,
      optimal_max: 10,
      sub_optimal_below_min: null,
      sub_optimal_above_max: null,
      action_below: null,
      action_above: null,
      explainer: "",
      source_citation: "r",
      confidence: 0.9,
    });
    const result = await autoGenerateDraftRange(mockCtx(), {
      nameOnReport: "X",
      rawUnit: "U/L",
      labPrintedRange: null,
      canonicalIdGuess: "x",
      queueOccurrenceCount: 5,
    });
    expect(result.outcome).toBe("rejected_bad_thresholds");
  });

  it("writes the range on happy path", async () => {
    vi.mocked(callAutoDraftRange).mockResolvedValue({
      is_real_biomarker: true,
      canonical_id: "ast_sgot",
      display_name: "AST",
      aliases: ["SGOT"],
      category: "Liver",
      canonical_unit: "U/L",
      sex: "any",
      age_min: 18,
      age_max: 120,
      pregnancy_sensitive: false,
      optimal_min: 10,
      optimal_max: 40,
      sub_optimal_below_min: 5,
      sub_optimal_above_max: 60,
      action_below: 3,
      action_above: 100,
      explainer: "AST is a liver enzyme.",
      source_citation: "NIH",
      confidence: 0.9,
    });
    const ctx = mockCtx("new-range-id");
    const result = await autoGenerateDraftRange(ctx, {
      nameOnReport: "Aspartate Aminotransferase",
      rawUnit: "U/L",
      labPrintedRange: "5-40",
      canonicalIdGuess: "ast_sgot",
      queueOccurrenceCount: 5,
    });
    expect(result.outcome).toBe("wrote_range");
    expect(result.canonicalId).toBe("ast_sgot");
    expect(ctx.runMutation).toHaveBeenCalledOnce();
  });
});
